name: qm_global
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  dio: ^5.2.1+1
  flutter_native_splash: ^2.3.1
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^5.1.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter_native_splash:
  color: "#000000"
  background_image_dark: assets/app/QM_background.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path_android: "assets/app/QM-thumb.png.webp"
  image_path_ios: "assets/app/QM-thumb.png.webp"

flutter: 
  assets: 
    - assets/
    - assets/icon/
    - assets/images/
    - assets/json/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Black.ttf
        - asset: assets/fonts/Nunito-BlackItalic.ttf
          style: italic
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 900
  uses-material-design: true

